## This workflow will build a Java project with Gradle
## For more information see: https://docs.github.com/en/actions/tutorials/build-and-test-code/java-with-gradle
#
#name: Java CI with Gradle
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        java: [ '8', '11', '17', '21', '25' ]
#    name: Java version ${{ matrix.Java }}
#
#    steps:
#      - uses: actions/checkout@v6
#      - name: Set up JDK ${{ matrix.Java }}
#        uses: actions/setup-java@v5
#        with:
#          java-version: ${{ matrix.java }}
#          # the distribution can be either 'adopt' or 'zulu'
#          distribution: 'zulu'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Run all jUnit tests with Gradle
#        run: ./gradlew test
#
#      - name: Create jar
#        run: ./gradlew jar
